export const quotesList = [
    {qId:  1,
      qText: "Better safe than sorry.",
        qAuthor: "Anonymous"},
    {qId:  2,
      qText: "To be or Not to be, that is the question." ,
        qAuthor: "Shakespeare"},
    {qId:  3,
      qText: "Be greedy when others are fearful; be fearful when others are greedy.",
        qAuthor: "Warren Buffet"},
    {qId:  4,
      qText: "If you're going through hell, keep going.",
        qAuthor: "Winston Churchill"},
    {qId:  5,
        qText: "These things I have spoken to you that in Me you may have peace. In the world you have affliction, but take courage; I have overcome the world.",
          qAuthor: "John 16:33"},
    {qId:  6,
        qText: "Our greatest glory is not in never falling, but in rising every time we fall.",
          qAuthor: "Confucius"},
    {qId:  7,
        qText: "I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear.",
          qAuthor: "Nelson Mandela"},
    {qId:  8,
        qText: "When the whole world is silent, even one voice becomes powerful.",
          qAuthor: "Malala Yousafzai"},
    {qId:  9,
          qText: "If you don’t like the road you’re walking, start paving another one.",
          qAuthor: "Dolly Parton"},
    {qId:  10,
          qText: "Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do.",
          qAuthor: "Mark Twain"},
    {qId:  11,
          qText: "Those who dare to fail miserably can achieve greatly.",
          qAuthor: "John F. Kennedy"},
    {qId:  12,
          qText: "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them. They went out and happened to things.",
          qAuthor: "Leonardo Da Vinci"},
    {qId:  13,
          qText: "Only put off until tomorrow what you are willing to die having left undone.",
          qAuthor: "Pablo Picasso"},
    {qId:  14,
          qText: "If you want to be happy, be.",
          qAuthor: "Leo Tolstoy"},
    {qId:  15,
          qText: "Never let the fear of striking out keep you from playing the game.",
          qAuthor: "Babe Ruth"},
    {qId:  16,
          qText: "Come to Me all who toil and are burdened, and I will give you rest.",
          qAuthor: "Matthew 11:28"},
    {qId:  17,
          qText: "For everyone who exalts himself shall be humbled, and he who humbles himself shall be exalted.",
          qAuthor: "Luke 14:11"},
    {qId:  18,
          qText: "Brothers, I do not account of myself to have laid hold; but one thing I do: Forgetting the things which are behind and stretching forward to the things which are before.",
          qAuthor: "Philippians 3:13"},
    {qId:  19,
          qText: "I have fought the good fight; I have finished the course; I have kept the faith.",
          qAuthor: "2 Timothy 4:7"},
    {qId:  20,
          qText: "If you buy things you do not need, soon you will have to sell things you need.",
          qAuthor: "Warren Buffet"},
  ];
