export const quotesList = [
    {qId:  1,
      qText: "Better safe than Sorry" ,
        qAuthor: "Anonymous"},
    {qId:  2,
      qText: "To be or Not to be. That is the question." ,
        qAuthor: "Shakespeare"},
    {qId:  3,
      qText: "Be greedy when others are fearful; be fearful when others are greedy",
        qAuthor: "Warren Buffet"},
    {qId:  4,
      qText: "If you're going through hell, keep going",
        qAuthor: "Winston Churchill"},
    {qId:  5,
        qText: "These things I have spoken to you that in Me you may have peace. In the world you have affliction, but take courage; I have covercome the world.",
          qAuthor: "John 16:33"},
    {qId:  6,
        qText: "Our greatest glory is not in never falling, but in rising every time we fall.",
          qAuthor: "Confucius"},
    {qId:  7,
        qText: "I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear",
          qAuthor: "Nelson Mandela"},
    {qId:  8,
        qText: "When the whole world is silent, even one voice becomes powerful.",
          qAuthor: "Malala Yousafzai"},
    {qId:  9,
          qText: "If you don’t like the road you’re walking, start paving another one.",
          qAuthor: "Dolly Parton"}
  ];
